  20181687.cpp
20181687.obj : error LNK2019: _mysql_errno@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
20181687.obj : error LNK2019: _mysql_error@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
20181687.obj : error LNK2019: _mysql_init@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
20181687.obj : error LNK2019: _mysql_real_connect@32_main 함수에서 참조되는 확인할 수 없는 외부 기호
20181687.obj : error LNK2019: _mysql_select_db@8_main 함수에서 참조되는 확인할 수 없는 외부 기호
20181687.obj : error LNK2019: _mysql_query@8"void __cdecl type1(void)" (?type1@@YAXXZ) 함수에서 참조되는 확인할 수 없는 외부 기호
20181687.obj : error LNK2019: _mysql_store_result@4"void __cdecl type1(void)" (?type1@@YAXXZ) 함수에서 참조되는 확인할 수 없는 외부 기호
20181687.obj : error LNK2019: _mysql_free_result@4"void __cdecl type1(void)" (?type1@@YAXXZ) 함수에서 참조되는 확인할 수 없는 외부 기호
20181687.obj : error LNK2019: _mysql_fetch_row@4"void __cdecl type1(void)" (?type1@@YAXXZ) 함수에서 참조되는 확인할 수 없는 외부 기호
20181687.obj : error LNK2019: _mysql_close@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
libmysql.lib : warning LNK4272: 'x64' 라이브러리 컴퓨터 종류가 'x86' 대상 컴퓨터 종류와 충돌합니다.
C:\Users\jiseo\OneDrive\바탕 화면\3학년 1학기\데이터베이스 시스템\prj2\Project2\Debug\Project2.exe : fatal error LNK1120: 10개의 확인할 수 없는 외부 참조입니다.
